name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: sudo apt-get update && sudo apt-get install make asciidoc asciidoctor dblatex
    - name: Build guide
      run: make
    - name: Upload generated files
      uses: actions/upload-artifact@v1.0.0
      with:
        name: output
        path: output
